### ISSUE TITLE
check-schedule is hardcoded

### ISSUE THREAD

**Issue by domcleal** [fac/fa-harness-tools#1]
`check-schedule` is mostly hardcoded behaviour and should be more configurable:

* The schedule itself is fixed Mon-Thu 9am-4pm, Fri 9-12, but it should be easy to set your own. Perhaps pass an argument that adds schedules, e.g. `--schedule "* 9-15 * * mon-thu" --schedule "* 9-11 * * fri"`
* The timezone is fixed to Europe/London

**Comment by RobBrownFreeAgent** [comment]
If this change in made, can the Data Warehouse application have its deploy window altered to:
- 8am-6pm Mon - Thur
- 8am-4pm Fri
- No deployments on the weekend

Then let Analytics know in #analytics-team-chat.

Thanks!
